version: '2'

volumes:
  jenkins-data-volume:

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        proxyHost: ${HTTP_PROXY_HOST}
        proxyPort: ${HTTP_PROXY_PORT}
        nexusLogin: ${NEXUS_LOGIN}
        nexusPass: ${NEXUS_PASSWD}
    image: company/jenkins:latest
    restart: always
    volumes:
      - jenkins-data-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_SLAVE_AGENT_PORT}:50000"