version: '3'

volumes:
  jenkins-data-volume:

services:
  jenkins:
    build:
      context: ./jenkins
      args:
        PROXY_HOST: ${HTTP_PROXY_HOST}
        PROXY_PORT: ${HTTP_PROXY_PORT}
        NEXUS_LOGIN: ${NEXUS_LOGIN}
        NEXUS_PASSWD: ${NEXUS_PASSWD}
    image: company/jenkins:latest
    restart: always
    volumes:
      - jenkins-data-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_SLAVE_AGENT_PORT}:50000"